baseurl = "https://csabazsolnai.github.io/hugo_website/"  # Include trailing slash
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."

theme = ["github.com/chipzoller/hugo-clarity"]
disqusShortname = ""
relativeURLs = true

DefaultContentLanguage = "en"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true