[[main]]
  name = "Blog"
  url = ""
  weight = -110

[[main]]
  name = "About Me"
  url = "about/"
  weight = -107

[[main]]
  name = "Projects"
  url = "projects/"
  weight = -107

[[main]]
  name = "Publications"
  url = "publications/"
  weight = -107

[[main]]
  name = "Contact"
  url = "contact/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/csabazsolnai"

[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/csaba-zsolnai-37727896/"
